version: '3'

services:
  my-service-demo-rabbitmq:
    image: rabbitmq:3.8.13-management
    container_name: my-service-demo-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: changeme
    ports:
      - "5672:5672"
      - "15672:15672"

  my-service-demo-mysql:
    image: mysql:5.6
    container_name: my-service-demo-mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=''
    restart: always
    ports:
      - '9306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dev
      TZ: Asia/Seoul

  my-service-demo-mongo:
    image: mongo:4.2
    container_name: my-service-demo-mongo
    ports:
      - '27017:27017'

  my-service-demo-redis:
    image: redis
    container_name: my-service-demo-redis
    command: redis-server --port 6379
    ports:
      - '6379:6379'
    restart: always
