version: '3'

services:
  my-service-demo-rabbitmq:
    image: rabbitmq:3.8.13-management
    container_name: my-service-demo-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: changeme
    ports:
      - "5672:5672"
      - "15672:15672"

  my-service-demo-mongo:
    image: mongo:4.2
    container_name: my-service-demo-mongo
    ports:
      - '27017:27017'

  my-service-demo-redis:
    image: redis
    container_name: my-service-demo-redis
    command: redis-server --port 6379
    ports:
      - '6379:6379'
    restart: always
